### ISSUE TITLE
context-menu entries change

### ISSUE THREAD

**Issue by dersphere** [XBMC-Addons/plugin.video.the.trailers#10]
ATM:
1. Show Movie Info
2. Add-on settings
3. Browse movies by year
4. Browse movies by studio
5. Browse movies by cast
6. Browse movies by genre
7. Download Trailer

I would suggest changing it to:
1. Show Movie Info
2. Add-on settings
3. Browse by genre
4. Download (Background)
5. Download + Play
6. Show downloads
7. Add to Couchpotato

Note sure if browsing by year, studio is needed. Browsing by cast will never be used I guess.
Thoughts?

**Comment by MartijnKaijser** [comment]
Drop 'browse by cast' definitely.

Year isn't really needed cause trailers are all from this+next year. It could be usefull when you also want to add already downloaded trailers which aren't in the list anymore and perhaps add more providers which offer older trailers to.
Perhaps comment it out so we could use it in future (or re-add it)

Studio is not that important and can't image it is used.

Download+play could also be a setting (like is was in old version)
Keep text 'Download (Background)' just as 'Download'.

**Comment by dersphere** [comment]
ok, Should I add the context-entry and plugin-view for couchpotato and you implement the queeup code and settings?

the "(Background)" was only for you, sure it will be named just "Download" :-)

**Comment by MartijnKaijser** [comment]
Sure add away and i'll hook it up

**Comment by dersphere** [comment]
btw. the filter-criterias (year, cast, genre, studio) are coded scraper-specific, means if we add another scraper which provides more or less criterias they will be shown automatically.

**Comment by MartijnKaijser** [comment]
ah yeah I forgot :P
Just keep year

**Comment by dersphere** [comment]
You mean "genre", right? ;-)

**Comment by MartijnKaijser** [comment]
hehe yep ;)

**Comment by dersphere** [comment]
solved with ba66ab6194b0c66385ea06dc44c757a54485b164
