### ISSUE TITLE
download&play

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#11]
Currently this follow the quality set by play while i would think it would follow the setting of download.

Option:
1. Leave it like it is
2. When download&play is chosen disable the play quality in settings so it is clear that one isn't used and use the quality set in the download section.

**Comment by dersphere** [comment]
Personally I prefer like it is now: stream/download-play uses stream-quality, downloading uses download-quality.

**Comment by MartijnKaijser** [comment]
ok
