### ISSUE TITLE
XML source files: Apple trailers

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#2]
for source in ( "currentt.xml", "current_480p.xml", "current_720p.xml", ):
http://trailers.apple.com/trailers/home/xml/current.xml

for source in ( "newest.xml", "newest_480p.xml", "newest_720p.xml", ):
http://trailers.apple.com/trailers/home/xml/newest.xml

Just this version
http://trailers.apple.com/trailers/home/xml/widgets/indexall.xml

**Comment by dersphere** [comment]
movie meta info including trailers in different resolutions per movie:
http://trailers.apple.com/moviesxml/s/<studio>/<title>/index.xml
http://trailers.apple.com/moviesxml/s/fox/prometheus/index.xml

**Comment by dersphere** [comment]
closing, its not an issue :)
