### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#3]
- found it how to access different trailer kinds for given movie (trailer 1, trailer 2)  (done)
- dynamic shortcuts in context menu on folders (start plugin next time here)  (done)
- dynamic folder bypass via settings (dont ask me the resolution, try 720p or better)  (done)
- downloading asynchron via simple-dowonloader module  (done)
- couchpotato
- xml caching  (done)
- add synchronous (foreground, blocking) download and or download-and-play functions and settings.
- track already (foreground or background) downloaded trailers for playback. (means, if a trailer is already downloaded, play local instead of remote)
- (maybe?) add context menu entry for "already downloaded trailers"
- (maybe?) change covers from xlarge to large (or next smaller size). (xlarge ones take to long to load (even from cache) and scale worse.

**Comment by dersphere** [comment]
1, 3 finished.

**Comment by dersphere** [comment]
2, 4, 6 finished.

only 5 still todo

**Comment by MartijnKaijser** [comment]
should i add the old couchpotato file again?
Some user did complain it didn't work with a new version.
However fixing it for the new might break the old one

**Comment by dersphere** [comment]
Not sure on the couchpotato stuff but I got it this way:
- "old" couchpotato file works with couchpotato
- It does not work with couchpotato-server (which is like a fork)

So if this is correct I suggest using the old file and adding new methods for couchpotato server. Then in the addon-settings there should be a switch for couchpotato|couchpotato-server.

**Comment by dersphere** [comment]
Still todo (but not on the above todo list):
7. add synchronous (foreground, blocking) download and or download-and-play functions and settings.
8. track already (foreground or background) downloaded trailers for playback. (means, if a trailer is already downloaded, play local instead of remote)
9. (maybe?) add context menu entry for "already downloaded trailers"
10. (maybe?) change covers from xlarge to large (or next smaller size). (xlarge ones take to long to load (even from cache) and scale worse.

**Comment by MartijnKaijser** [comment]
Well i'd say add couchpotato and worry about the server part later on.

think a sub subsetting "couchpotato server" would do.
other option is to use "off|couchpotato|couchpotato" and show the needed settings

Not sure what is needed extra for the server part

**Comment by MartijnKaijser** [comment]
1. Not sure if that's really necessary. Clutters the menus to much i think. There are already much context options. Think 7 covers most use cases. Better option would be to download all non-local trailers in list (perhaps limited by genre although that would make it very tricky with all possibilities).
2. If i'm correct xlarge is only 540px × 800px so it's already borderline. Wouldn't go smaller. I have no problems with sluggish loading of them from cache.

New one:
11.  When starting plugin it says retrieving '0' and it doesn't increase. Would be better it would show actual numbers. Same for entering the movie folder with possible trailers

**Comment by MartijnKaijser** [comment]
Regarding 5.Couchpotato
Maybe this could be usefull in some way.
https://github.com/queeup/plugin.video.imdb.trailers/blob/eden/addon.py#L219

**Comment by dersphere** [comment]
-5. ok - looks good. Can you ask queeup and implement it?
-8. solved with c6f8550
-9. Which list, especially how to open that? I think of a context-menu entry like "Already downloaded Trailers" which will open a list.
-10. ok. (btw. 120kb each cover, 130 movies means 15MB)
-11. Not possible. We have nothing to (easy) iterate over. Even if the building of list-items (which would be iterable) would be the bottleneck (which isn't; xml retrieving, xml-de-serializing is), the scraper-modules (ex. apple-scraper.py) would need callback methods to the addon-part of code or the xbmcswift framework. This would make the code much more complex.

**Comment by MartijnKaijser** [comment]
-5 wil ask and implement. Shouldn't be a problem cause it's also has the do whatever you want license. I'll add a thank you note.

-9 Like discussed in #10

-10 Never heared any one complain and the normal size just looks way to crappy on large screen with large poster view.

-11 Ok just a tought

**Comment by dersphere** [comment]
still anything open? Lost the overview ;)

**Comment by MartijnKaijser** [comment]
only no 53

Edit:
normal CP works. only server doesn't
Will look at that when i have a chance (or we let some one else fix it because i have no way of testing his)

**Comment by MartijnKaijser** [comment]
Anything else that needs to be done?
Besides the "show downloads" which can be hidden for now until a next update.

**Comment by MartijnKaijser** [comment]
watched status fix is available btw
   see XBMC PR 1083

**Comment by zeubs** [comment]
thanks to  MartijnKaijser ando thers who have contributed.
May I ask if couchpotatoServer integration is still in the works?

**Comment by zeubs** [comment]
Couchpotato v2 (server edition) has an integrated API, documentation available online or if you have it installed at
 http:// < couchpotato IP > :port/docs. Thought it might help.
