### ISSUE TITLE
keeps playing same trailer

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#4]
Haven't gone into it yet but while just running it keeps playing the first trailer you played no matter what movie you pick and if you exit the plugin.

So if you had played trailer X and want to play trailer Y it keeps playing trailer X

**Comment by dersphere** [comment]
log?

**Comment by MartijnKaijser** [comment]
http://xbmclogs.com/show.php?id=2074

around 1134 you see i select Bad Ass and it play and finishes without problems.
around line 1432 i selected Total Recall and on line 1449 you see it start playing Bad Ass

Another thing I noticed is that when there is no internet connection that you get an error exception which isn't caught.
http://xbmclogs.com/show.php?id=2075
Same for XBMC logs uploader
