### ISSUE TITLE
directly play trailer if only one is available

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#7]
just as a reminder

**Comment by dersphere** [comment]
Won't be doable or at least not easy. Plugins need to set isPlayable True|False to each ListItem while showing it. We cant know if a movie has one or more than one Trailer-Types before getting the "self.MOVIE_URL % movie['movie_string']" file.

**Comment by MartijnKaijser** [comment]
well it's not a requirement nor important. Just something that came to mind :)
perhaps someday we will have a brilliant idea on how to do this

**Comment by dersphere** [comment]
solved with the dialog-method
