### ISSUE TITLE
exception: Multiple matches in get_single_movie!

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#8]
Something i came accros

http://xbmclogs.com/show.php?id=2226

**Comment by dersphere** [comment]
I guess this log was only accessible 7 days...
Did you remember the video-title?

**Comment by MartijnKaijser** [comment]
Redemption

**Comment by dersphere** [comment]
funny.
'movie_id': u'4881', 'title': u'Redemption'
'movie_id': u'4801', 'title': u'The Raid: Redemption'

I will fix with search for exact matches (and not partially matches) in the get_single_movie() method.

**Comment by MartijnKaijser** [comment]
well these are the weird ones that make testing it yourself make it worth before pushing to repo :)
