### ISSUE TITLE
xbmcswift: raise NotFoundException

### ISSUE THREAD

**Issue by MartijnKaijser** [XBMC-Addons/plugin.video.the.trailers#9]
http://xbmclogs.com/show.php?id=2385

This error happens when scrolling through the DialogVideoInfo window in Aeon Nox.
Relevant log message:
        StartScript - calling plugin The Trailers('plugin://plugin.video.the.trailers/extrafanart/','0','')

How to fix:
1. let skin handle/fix this
2. create our own 'extrafanart' folder
3. Other suggestions?

**Comment by MartijnKaijser** [comment]
This one is solved in the solved in the skin.
Not sure if other skins also gonna experience this behaviour.

**Comment by dersphere** [comment]
Skin issue.

Aeon Nox should either skip retrieving of extrafanart subdirs for virtual folders (plugin://...) or check in any way if a folder exists before accessing it.

Btw. this message takes place in any xbmcswift addon (because it (virtually) extends the VFS)...
